### PR TITLE
New ping API

### PR DESCRIPTION
**Pull request by owlishDeveloper**
@imbstack @djmitche  r?

### CODE REVIEW

**Comment by jonasfj** [comment]
Same problem as in the tc-queue... This use api through base... we should move from base to use API directly.

**Comment by jonasfj** [comment]
Run the tests you'll need credentials:
https://github.com/taskcluster/taskcluster-index/blob/master/user-config-example.yml

Just create a `user-config.yml` file...

There is still a lot of `base.API` references in the code.

**Comment by owlishDeveloper** [comment]
I think I got them all now - at least local tests are passing!

**Comment by owlishDeveloper** [comment]
Cool, squashing worked!! Neat! Thank you again for help, @djmitche ! 

Tests are passing successfully here. r?

**Comment by jonasfj** [comment]
Let's hope heroku won't deploy if test fail...

**Pull request merged**
