### PR TITLE
return non expired results from findTask and findNamespace

### PR DESCRIPTION
**Pull request by tuhina2020**
https://bugzilla.mozilla.org/show_bug.cgi?id=1451548

@djmitche

### CODE REVIEW

**Comment by tuhina2020** [comment]
@djmitche I need some help understanding the error messages in test

```
  api:errors Error occurred handling: /tasks/my-ns, err: TypeError: op.operand.getTime is not a function, as JSON: {}, incidentId: fd330c9f-7778-4440-bf48-4f396a574dfb TypeError: op.operand.getTime is not a function
    at DateType.compare (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/azure-entities/lib/entitytypes.js:365:75)
    at /Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/azure-entities/lib/inmemory.js:189:31
    at arrayEvery (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/lodash/lodash.js:579:12)
    at Function.every (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/lodash/lodash.js:9148:14)
    at /Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/azure-entities/lib/inmemory.js:188:16
    at arrayFilter (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/lodash/lodash.js:603:11)
    at Function.filter (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/lodash/lodash.js:9190:14)
    at InMemoryWrapper.queryEntities (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/azure-entities/lib/inmemory.js:200:18)
    at fetchResults (/Users/sudiptachatterjee/WorkSpace/taskcluster-index/node_modules/azure-entities
```

**Comment by djmitche** [comment]
That took some staring-at!  What it's saying is that `op.operand` doesn't have a `getTime` method, suggesting it's not a Date object.  Looking at that line in entitytypes.js, I see that `op` is passed from inmemory.js, where it seems to be the second argument.  Looking at your patch, I see `Entity.op.greaterThanOrEqual(new Date().toJSON()),` which is creating a new operator (op) with operand `new Date().toJSON()` -- a string.  I guess it wants a Date object, instead.

So I'm betting that just removing `.toJSON()` in all of those lines you've added would fix it?

**Comment by tuhina2020** [comment]
@djmitche fixed the tests

**Comment by djmitche** [comment]
I like that green checkmark!  I'll review shortly.

**Pull request merged**
